---
title: NEUROCOGNITIVE EXAMINATION
patient: Biggie
name: Smalls, Biggie
doe: {{< var doe >}}
date_of_report: {{< var date_of_report >}}
---

```{r}
#| label: setup
#| include: false
#| cache: false

packages <- c(
  "dplyr",
  "glue",
  "gt",
  "here",
  "janitor",
  "knitr",
  "purrr",
  "quarto",
  "readr",
  "readxl",
  "rmarkdown",
  "snakecase",
  "stringr",
  "tidytable",
  "vroom",
  "xfun",
  "bwu",
  "NeurotypR"
)

# Function to load packages one by one
load_packages <- function(packages) {
  for (pkg in packages) {
    if (!require(pkg, character.only = TRUE)) {
      install.packages(pkg)
      library(pkg, character.only = TRUE)
    }
    message(paste("Loaded package:", pkg))
  }
}

# Call the function to load packages
load_packages(packages)

# Set knitr options
knitr::opts_knit$set(
  width = 80,
  digits = 2,
  warnPartialMatchArgs = FALSE,
  crop = knitr::hook_pdfcrop,
  optipng = knitr::hook_optipng
)

# Set environment variables with default values
Sys.setenv(PATIENT = "{{< var patient >}}")
patient <- Sys.getenv("PATIENT")
```

```{r}
#| label: data-load
#| include: false

file_path <- here::here("data", "csv")
bwu::load_data(here::here(file_path))
neuropsych <- readr::read_csv("neuropsych.csv")
neurocog <- readr::read_csv("neurocog.csv")
neurobehav <- readr::read_csv("neurobehav.csv")
validity <- readr::read_csv("validity.csv")
```

```{=typst}
#let name = [{{< var last_name >}}, {{< var first_name >}}]
#let doe = [{{< var date_of_report >}}]
#let patient = [{{< var patient >}}]
// #v(2em, weak: true)
// #show block: set par(leading: 0.65em)
#block[
// *CASE NUMBER*: {{< var case_number >}} \
*PATIENT NAME:* #name \
*DATE OF BIRTH:* {{< var dob >}}, Age {{< var age >}} \
*DATES OF EXAM:* {{< var doe >}}, {{< var doe2 >}}, and {{< var doe3 >}} \
*DATE OF REPORT:* {{< var date_of_report >}} \
]
```
{{< include sections/_00-00_tests.qmd >}}

<!-- {{< pagebreak >}} -->

{{< include sections/_01-00_nse_adult.qmd >}}

<!-- {{< pagebreak >}} -->

{{< include sections/_02-00_behav_obs.qmd >}}

```{=typst}
= NEUROCOGNITIVE FINDINGS
```
<!-- {{< pagebreak >}} -->

{{< include sections/_03-00_sirf.qmd >}}

{{< include sections/_03-00_sirf_text.qmd >}}

{{< include sections/_03-01_recommendations.qmd >}}

{{< include sections/_03-02_signature.qmd >}}

<!-- {{< pagebreak >}} -->

{{< include sections/_03-03_appendix.qmd >}}
